### ISSUE TITLE
[Question]performence comparison with apache/brpc and tencent/flare?

### ISSUE THREAD

**Issue by wanghenshui** [trpc-group/trpc-cpp#102]
trpc-cpp better than flare?

**Comment by helloopenworld** [comment]
The performance of a framework depends more on whether the framework is suitable for business scenarios. Performance comparisons without business scenarios are meaningless.

**Comment by helloopenworld** [comment]
trpc currently performs relatively well in these high-performance business scenarios within Tencent.
<img width="989" alt="image" src="https://github.com/trpc-group/trpc-cpp/assets/22511535/24d3a8fe-b033-4f99-bf87-faf9fa8bfb5f">
