### ISSUE TITLE
加密与鉴权

### ISSUE THREAD

**Issue by city-invoker** [trpc-group/trpc-cpp#122]
trpc协议是怎么支持消息的加密与鉴权的，通过filter来实现的话，那不是会在filter阶段多进行一次数据的反序列化？

**Comment by liucf3995** [comment]
trpc协议默认是明文传输的，协议本身没有提供鉴权。
业务侧可以通过透传信息字段来扩展。比如，可以通过透传信息字段来传输鉴权Token信息，然后结合Filter在合适的时机注入Token或者校验同Token的合法性。是否存在额外的数据序列化、反序列化和具体的鉴权方案有关，有的方案不需要额外的序列化开销。
