### ISSUE TITLE
【腾讯犀牛鸟计划】在tRPC-Cpp的2种runtime下发起对2个下游的调用

### ISSUE THREAD

**Issue by weimch** [trpc-group/trpc-cpp#135]
## issue介绍
tRPC-Cpp提供了协程runtime，用于CPU密集的场景，使用同步编程；框架也提供了线程runtime，用于IO密集的场景，使用Future-Promise异步编程。

你需要使用这两种编程方式分别发起对2个下游服务的调用，并使用腾讯文档输出一份报告到issue回复里，报告需要包含你的实践过程（关键的代码以及日志输出等）以及不同编程方式的使用体会，最后提交相关变更代码到你个人的repo以及编译运行指引到issue回复里，方便我们测试验证你的确完成了issue。

具体地，你可以按下面的步骤完成此issue
1、使用examples/helloworld作为下游，在此基础上，新增一个service，创造两个下游服务。
2、使用examples/features/fiber_forward作为协程runtime的中转服务，在此服务里，使用fiber的工具（查阅fiber用户指南），并发调用两个下游。
3、使用examples/features/future_forward作为线程runtime的中转服务，在此服务里，使用future的Then链（查阅future用户指南），串行地调用两个下游。
4、【可选】除此之外，fiber和future用户指南里，提供了很多易用的接口，你能使用不同于2/3的方式，调用两个下游的调用吗？

## 参考资料
1、runtime介绍：https://github.com/trpc-group/trpc-cpp/blob/main/docs/zh/runtime.md
2、fiber用户指南：https://github.com/trpc-group/trpc-cpp/blob/main/docs/zh/fiber_user_guide.md
3、future用户指南：https://github.com/trpc-group/trpc-cpp/blob/main/docs/zh/future_promise_guide.md

## 其他说明
**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。

**Comment by mmiemm** [comment]
已成功领取本issue

**Comment by Heaven2024** [comment]
您好，请问这里的要求是否是将如下的代码更改为并发调用两个服务？以fiber举例：
<img width="926" alt="image" src="https://github.com/user-attachments/assets/6a9660d5-d02b-4427-bdfc-df630935d18c">
新增服务是否是这样定义进行实现呢:)
<img width="570" alt="image" src="https://github.com/user-attachments/assets/ac93391b-305b-430f-b434-5489f56a1b70">

**Comment by weimch** [comment]
> 您好，请问这里的要求是否是将如下的代码更改为并发调用两个服务？以fiber举例： <img alt="image" width="926" src="https://private-user-images.githubusercontent.com/127117846/352047340-6a9660d5-d02b-4427-bdfc-df630935d18c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjE1MjMsIm5iZiI6MTcyMTk2MTIyMywicGF0aCI6Ii8xMjcxMTc4NDYvMzUyMDQ3MzQwLTZhOTY2MGQ1LWQwMmItNDQyNy1iZGZjLWRmNjMwOTM1ZDE4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMjMzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzEzYjQwZjEyNzRhZDI2ODQ3MzQyYmIyMWMxZjBmY2U5ZjhmZTFjODYwYjhlODE4M2IyNWQxODdlNjVhMjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uroiXGM6Jnc9hDRsr-9b5nYZIIZBHl1pAl29N2Wq7Os"> 新增服务是否是这样定义进行实现呢:) <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/127117846/352048483-ac93391b-305b-430f-b434-5489f56a1b70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjE1MjMsIm5iZiI6MTcyMTk2MTIyMywicGF0aCI6Ii8xMjcxMTc4NDYvMzUyMDQ4NDgzLWFjOTMzOTFiLTMwNWItNDMwZi1iNDM0LTU0ODlmNTZhMWI3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMjMzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjBiNDBlMDZmNjYyOTBmYmJjZjU5ZmQ4MWJlODU5ZGI5YWUwZjFlYjUxYTVjYjNmMWFlMmU4Njc3NDUxNTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-YigPcPgwU6FFjq0FiquUo4x3aTG5rok3u5rM3NkMHk">

并发调用你找的代码片段没错（注意用FiberLatch来等待并发调用结束），新增服务可以这样定义。

**Comment by Heaven2024** [comment]
修改/新增proto文件添加服务需要重新生成c++文件吧？ 然后forward的proto文件也需要修改，这是没问题的吧，担心方法错了

**Comment by weimch** [comment]
> 修改/新增proto文件添加服务需要重新生成c++文件吧？ 然后forward的proto文件也需要修改，这是没问题的吧，担心方法错了

1. 改proto文件之后，编译会自动重新生成*.trpc.pb.h/cc文件。
2. forward的proto文件不需要修改，你需要在forward的一个rpc接口实现里，发起两次下游调用（比如你这个rpc接口，需要调用两个下游，组合数据，然后返回响应）

**Comment by Heaven2024** [comment]
感谢解答，这边测试完成效果如下，是否达到要求
<img width="943" alt="image" src="https://github.com/user-attachments/assets/34d5b1ac-3f9a-4ff5-a2d4-256e980bcb76">

**Comment by weimch** [comment]
> 感谢解答，这边测试完成效果如下，是否达到要求 <img alt="image" width="943" src="https://private-user-images.githubusercontent.com/127117846/352520959-34d5b1ac-3f9a-4ff5-a2d4-256e980bcb76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjM2NzQsIm5iZiI6MTcyMjA2MzM3NCwicGF0aCI6Ii8xMjcxMTc4NDYvMzUyNTIwOTU5LTM0ZDViMWFjLTNmOWEtNGZmNS1hMmQ0LTI1NmU5ODBiY2I3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNjU2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2QwMmE2MjRlMTE2MWQ4MTJlMDA2OWZjYjVlNDRmZDMxNGRhYWUwMjliZDI3ZjI0MjM3OWM2MWQ0NDEzNTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kZDYYBC7f7un2cg7PoTUOqzQjZBCXgjk2K6_xrLN_n0">

future_forward也需要开发下（这个用Future-Then链串起来调）

**Comment by Heaven2024** [comment]
你好，这边的future代码测试出现了如下问题：
<img width="796" alt="image" src="https://github.com/user-attachments/assets/4b2b187e-f391-48cc-9a00-2e1004dfa156">
串行调用的实现代码为：
<img width="782" alt="image" src="https://github.com/user-attachments/assets/b21014a8-7d35-4a31-8a33-cbff702cbeb7">
<img width="698" alt="image" src="https://github.com/user-attachments/assets/0cd53152-7196-43f1-874f-4194ed530800">
是什么原因呢 yaml配置和fiber类似

**Comment by Heaven2024** [comment]
已完成issuse要求步骤，相关代码在个人仓库分支[runtime](https://github.com/Heaven2024/trpc-cpp/tree/runtime)
测试步骤：
`git clone https://github.com/Heaven2024/trpc-cpp && git checkout runtime 
`测试运行fiber：
`. run_fiber.sh
`测试运行future：
`. run_future.sh`

**Comment by Heaven2024** [comment]
正在编写中

**Comment by Heaven2024** [comment]
你好，对于fiber我有一个疑问，如下输出是预期的行为吗，按我的理解两个并发调用的输出应该符合先后的顺序（again应该在之后）
<img width="616" alt="image" src="https://github.com/user-attachments/assets/e0773758-fbba-4553-ae40-ea13146315c6">

**Comment by weimch** [comment]
> 你好，对于fiber我有一个疑问，日志中会有如下输出，是预期的行为吗？按我的理解两个并发调用的输出应该符合先后的顺序（again应该在之后） <img alt="image" width="616" src="https://private-user-images.githubusercontent.com/127117846/354314818-e0773758-fbba-4553-ae40-ea13146315c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODM2ODUsIm5iZiI6MTcyMjU4MzM4NSwicGF0aCI6Ii8xMjcxMTc4NDYvMzU0MzE0ODE4LWUwNzczNzU4LWZiYmEtNDU1My1hZTQwLWVhMTMxNDYzMTVjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNzIzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTAwYWY0Njg4OGVlNWE0ZTFlODNkMjFmYmYzMzg2OWY0MGJkNmI5M2VmMDBjYzE1MDdjZmExNmJlNTljMzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nl_DXtYWKUPpLjqH0TNy7CzoMKpqt2HuVYGprMQDXcE"> 这是并发调用代码 <img alt="image" width="777" src="https://private-user-images.githubusercontent.com/127117846/354315830-7a888c90-5376-4c41-9565-a72a1e9e5f2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODM2ODUsIm5iZiI6MTcyMjU4MzM4NSwicGF0aCI6Ii8xMjcxMTc4NDYvMzU0MzE1ODMwLTdhODg4YzkwLTUzNzYtNGM0MS05NTY1LWE3MmExZTllNWYyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNzIzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTkxMWEzMTZhY2U4ZmYxZTgxYTIxMjA3NmNmMWI3NzZkYWNhM2RhMjVlMDk2MjgyOTM2ZjVkNjFlMjg0YTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sgZBmvgSJz2Jh9MXpS-gUhCUscmxQMCpJoceEZrp-9A">

符合预期的，fiber是并发的，谁先谁后执行不一定。

**Comment by Heaven2024** [comment]
我想错了，感谢解答，报告已完成：
【腾讯文档】【腾讯犀牛鸟计划】在tRPC-Cpp的2种runtime下发起对2个下游的调用
https://docs.qq.com/aio/DT3NJc2ltZWdmSHdF

**Comment by weimch** [comment]
已经测试通过，文档写得很完善，此issue由 @Heaven2024 完成。
