### ISSUE TITLE
【腾讯犀牛鸟计划】实现IP直连负载均衡插件 - hash算法

### ISSUE THREAD

**Issue by weimch** [trpc-group/trpc-cpp#141]
## issue介绍

作为一种常见的服务治理措施，负载均衡算法能根据将请求分发到不同的服务器里，尽可能提高集群的处理请求量级。

不同的负载均衡算法适用于不同的业务场景，哈希算法适用于总是把相同客户端的请求，发到同一个下游里，适合于需要保持会话的场景。

你需要开发一个加权轮询的负载均衡器，并提PR共建到tRPC-Cpp中。

具体地，你可以参考下面的步骤进行开发
1、继承抽象类LoadBalance，实现负载均衡插件。
2、新增负载均衡的配置项，比如可以指定的哈希算法，用于哈希计算的内容，配置项细节你可以参考其他项目来构思，你需要结合此配置项，调用负载均衡插件的Update将信息传入到负载均衡插件中。
2、在yaml的loadbalance选项中，设置使用你的负载均衡插件，进行调测。

## 参考资料

1、框架当前已经实现了负载均衡插件：trpc/naming/common/util/loadbalance

## 其他说明

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。

**Comment by Polaris3003** [comment]
已成功领取本issue

**Comment by weimch** [comment]
已经实现并合入

https://github.com/trpc-group/trpc-cpp/pull/158
