### ISSUE TITLE
【腾讯犀牛鸟计划】实现过载保护插件 - 固定时间窗口

### ISSUE THREAD

**Issue by weimch** [trpc-group/trpc-cpp#142]
## issue介绍

作为实现服务高可用的一部分，过载保护算法是一种常用手段，能在请求激增的时候防止服务过载导致的性能急剧恶化甚至崩溃。

不同的负载均衡算法适用于不同的业务场景，固定时间窗算法的实现原理是，统计固定时间周期内的请求量，超过限额就会启动限流，因其实现简单有效而被应用较多。

你需要开发一个固定时间窗口的过载保护插件，并提PR到tRPC-Cpp中。

具体地，你可以参考下面的步骤进行开发
1、继承抽象类ServerOverloadController，实现过载保护插件。
2、实现server filter，调用过载保护插件。
3、用于测试验证，你可以复用examples/helloworld的代码来做测试，用在yaml里为服务配置server filter，额外的，你还需要改写fiber_client客户端代码，让其并发发送请求，提高并发量触发过载保护的效果。

## 参考资料

1、需要基于框架当前提供的过载保护的抽象类开发：trpc/overload_control/server_overload_controller.h

## 其他说明

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。

**Comment by Sunburst7** [comment]
已成功领取本issue

**Comment by fengyusen** [comment]
已成功领取本issue

**Comment by Heaven2024** [comment]
已成功领取本issue

**Comment by Heaven2024** [comment]
没有明白这里的`2.实现server filter，调用过载保护插件。`  我目前的实现是在服务端直接集成了过载保护插件，具体在`helloworld_server.cc`中，我将实现的逻辑包装进了了`GreeterServiceImpl`通过   ` auto overloadControlledGreeterService = std::make_shared<OverloadControlledGreeterService>(greeterService, overloadController);`请问这样实现是否符合要求，或者可以进一步说明一下server filter的逻辑？

**Comment by weimch** [comment]
> 没有太理解这里的`2.实现server filter，调用过载保护插件。` 我目前的实现是在服务端直接集成了过载保护插件，具体在`helloworld_server.cc`中，我将实现的逻辑包装进了了`GreeterServiceImpl`通过 ` auto overloadControlledGreeterService = std::make_shared<OverloadControlledGreeterService>(greeterService, overloadController);`请问这样实现是否符合要求，或者可以进一步说明一下server filter的逻辑？感谢

不符合要求哈，rpc框架通过拦截点扩展功能，具体是可以在rpc前后执行一些自定义的逻辑，实现server filter就是接入到这个拦截点的方法，你可以参考trpc-cpp提供的拦截器文档来实现，但需要继承server_overload_controller实现过载保护逻辑，并用server filter调用他。

https://github.com/trpc-group/trpc-cpp/blob/main/docs/README.zh_CN.md

<img width="380" alt="image" src="https://github.com/user-attachments/assets/fdafd2be-2e0a-445b-bc6c-b65706eb3731">

**Comment by Heaven2024** [comment]
你好，目前我将插件的逻辑都实现了，测试也没有问题
<img width="487" alt="image" src="https://github.com/user-attachments/assets/5267dd98-f843-455c-a5b6-b143d3a1e917">
但是用example进行测试时没能触发过载保护逻辑，请问哪里会有问题，包括我测试了现有的`concurrency_limiter`也没有触发，想问下原因怎么排查？
服务端注册：
<img width="850" alt="image" src="https://github.com/user-attachments/assets/83142ca1-9b69-4425-837b-bb755ecf389b">
客户端：
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/0e2f2fe0-4d74-4e66-a085-1ed6135ab72c">

**Comment by weimch** [comment]
yaml文件里是不是没有填filter？

https://github.com/tracer07/trpc-cpp/blob/test/docs/zh/filter.md

<img width="400" alt="image" src="https://github.com/user-attachments/assets/5baef693-2bfb-44d6-abfa-20b153f30664">

**Comment by Heaven2024** [comment]
> yaml文件里是不是没有填filter？
> 
> https://github.com/trpc-group/trpc-cpp/blob/main/docs/zh/filter.md
> 
> <img alt="image" width="400" src="https://private-user-images.githubusercontent.com/28728444/351212241-5baef693-2bfb-44d6-abfa-20b153f30664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjE0OTEsIm5iZiI6MTcyMTcyMTE5MSwicGF0aCI6Ii8yODcyODQ0NC8zNTEyMTIyNDEtNWJhZWY2OTMtMmJmYi00NGQ2LWFiZmEtMjBiMTUzZjMwNjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3NTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDRkNDA1ZDJhN2JkYzUwZjVhZTE4MzZhYzdlY2I2NjdkMTNmYzI4ZDFlMzZkYzFlZTU4ZmRjNzQ0MWUzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fN8_eAhnio-hspr_DNxK6hcCJyyqvNcM9ldTMs03hII">

<img width="799" alt="image" src="https://github.com/user-attachments/assets/e852727c-cb05-43c0-abb5-73f96dba3f7f">

**Comment by leolin49** [comment]
是不是 [.brazelrc中的编译选项](https://github.com/trpc-group/trpc-cpp/blob/81bf7174abce53f7b8504377cacc0ff192533f6a/docs/zh/overload_control_concurrency_limiter.md#%E7%BC%96%E8%AF%91%E9%80%89%E9%A1%B9) 没加

**Comment by Heaven2024** [comment]
> 是不是 [.brazelrc中的编译选项](https://github.com/trpc-group/trpc-cpp/blob/81bf7174abce53f7b8504377cacc0ff192533f6a/docs/zh/overload_control_concurrency_limiter.md#%E7%BC%96%E8%AF%91%E9%80%89%E9%A1%B9) 没加
加了的，要不然test文件也没法成功运行0.0

**Comment by weimch** [comment]
感觉文档写得有问题，看了下代码，在service里配置的话，要这样填

```yaml
server:
    service:
       - name: xxx
          service_filters:
             - fixedwindow_limiter
```

**Comment by shenh09** [comment]
已成功领取本issue
