### ISSUE TITLE
compile trpc-cpp on centos 7.9 failed

### ISSUE THREAD

**Issue by zanlichard** [trpc-group/trpc-cpp#58]
ERROR: /root/.cache/bazel/_bazel_root/de3aeab5343b6e0969660d47054e8920/external/com_github_google_flatbuffers/BUILD.bazel:30:1: no such target '@platforms//os:openbsd': target 'openbsd' not declared in package 'os' (did you mean 'freebsd'?) defined by /root/.cache/bazel/_bazel_root/de3aeab5343b6e0969660d47054e8920/external/platforms/os/BUILD and referenced by '@com_github_google_flatbuffers//:platform_openbsd'
ERROR: Analysis of target '//trpc/util/flatbuffers:trpc_fbs' failed; build aborted: Analysis failed

**Comment by raychen911** [comment]
https://stackoverflow.com/questions/72567182/bazel-rules-cc-no-such-target-platforms-oswasi-target-wasi-was-not-declare

可以列一下bazel版本吗？

**Comment by zanlichard** [comment]
[root@VM-0-2-tencentos external]# bazel --version
bazel 1.2.1

**Comment by raychen911** [comment]
> [root@VM-0-2-tencentos external]# bazel --version bazel 1.2.1

本地bazel版本bazel 3.7.0版本编译后“external/platforms/os/BUILD”里面存在openbsd目标
<img width="814" alt="image" src="https://github.com/trpc-group/trpc-cpp/assets/15060148/b4dde0c5-f337-4e0d-be9f-369c59d37fba">
<img width="273" alt="image" src="https://github.com/trpc-group/trpc-cpp/assets/15060148/9e3ea68d-7e82-4a91-9d21-219efa39da06">
有可能是你的bazel版本太低，升级一下看看？
