### ISSUE TITLE
trpc-cpp中的bazel编译的结果是什么

### ISSUE THREAD

**Issue by zanlichard** [trpc-group/trpc-cpp#59]
librpc.a还是librpc.so?

**Comment by helloopenworld** [comment]
不是，代码是源码依赖编译的，每个代码文件基本有独立的编译目标规则，如果是编译产物是静态库的话，可以用cmake

**Comment by zanlichard** [comment]
cmake编译的话,就需要自己手安装依赖对吧

**Comment by weimch** [comment]
> cmake编译的话,就需要自己手安装依赖对吧

可以参考[文档](https://github.com/trpc-group/trpc-cpp/blob/main/docs/zh/bazel_or_cmake.md#%E4%BD%BF%E7%94%A8cmake%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE)，默认是编译出libtrpc.a，你也可以开启动态编译。

可以通过FetchContent使用，也可以通过make install使用。
