### ISSUE TITLE
tencentOS Server relealse 3.1 编译失败

### ISSUE THREAD

**Issue by zanlichard** [trpc-group/trpc-cpp#61]
ERROR: /home/lichard/trpc-cpp/trpc/tracing/BUILD:19:11: Compiling trpc/tracing/tracing_factory.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 39 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error: trpc/tracing/tracing_factory.cc: Permission denied
gcc: fatal error: no input files
compilation terminated.

**Comment by helloopenworld** [comment]
gcc命令能正常执行不？

**Comment by zanlichard** [comment]
可以的

**Comment by zanlichard** [comment]
/root/.cache/bazel/_bazel_root/install/307a148e450f85a580a4875871de65e4/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/de3aeab5343b6e0969660d47054e8920/sandbox/linux-sandbox/28/execroot/trpc_cpp -w /tmp -w /dev/shm -D -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/trpc/tracing/_objs/tracing_factory/tracing_factory.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/trpc/tracing/_objs/tracing_factory/tracing_factory.pic.o' -fPIC -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_DISABLE_DEFAULT_LOGGER -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/com_github_fmtlib_fmt -iquote bazel-out/k8-fastbuild/bin/external/com_github_fmtlib_fmt -iquote external/com_github_jbeder_yaml_cpp -iquote bazel-out/k8-fastbuild/bin/external/com_github_jbeder_yaml_cpp -iquote external/com_github_gabime_spdlog -iquote bazel-out/k8-fastbuild/bin/external/com_github_gabime_spdlog -Ibazel-out/k8-fastbuild/bin/external/com_github_fmtlib_fmt/_virtual_includes/fmtlib -Ibazel-out/k8-fastbuild/bin/external/com_github_gabime_spdlog/_virtual_includes/spdlog -isystem external/com_github_jbeder_yaml_cpp/include -isystem bazel-out/k8-fastbuild/bin/external/com_github_jbeder_yaml_cpp/include -O2 '--std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c trpc/tracing/tracing_factory.cc -o bazel-out/k8-fastbuild/bin/trpc/tracing/_objs/tracing_factory/tracing_factory.pic.o)
1698046515.079227186: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1698046515.079253285: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1698046515.079453972: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 454989
1698046515.079476244: src/main/tools/linux-sandbox-pid1.cc:447: Pid1Main started
1698046515.079566283: src/main/tools/linux-sandbox-pid1.cc:189: working dir: /root/.cache/bazel/_bazel_root/de3aeab5343b6e0969660d47054e8920/sandbox/linux-sandbox/28/execroot/trpc_cpp
1698046515.079578656: src/main/tools/linux-sandbox-pid1.cc:221: writable: /root/.cache/bazel/_bazel_root/de3aeab5343b6e0969660d47054e8920/sandbox/linux-sandbox/28/execroot/trpc_cpp
1698046515.079584667: src/main/tools/linux-sandbox-pid1.cc:221: writable: /tmp
1698046515.079590107: src/main/tools/linux-sandbox-pid1.cc:221: writable: /dev/shm
1698046515.079662885: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /
1698046515.079671100: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys
1698046515.079676180: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/security
1698046515.079683073: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup
1698046515.079688814: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/systemd
1698046515.079694254: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/net_cls,net_prio
1698046515.079699143: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/perf_event
1698046515.079703932: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/cpuset
1698046515.079708510: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/hugetlb
1698046515.079713239: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/pids
1698046515.079718008: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/blkio
1698046515.079722697: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/devices
1698046515.079760177: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/cpu,cpuacct
1698046515.079765718: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/memory
1698046515.079770437: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/freezer
1698046515.079775376: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/pstore
1698046515.079780505: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/bpf
1698046515.079785264: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/config
1698046515.079789923: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/debug
1698046515.079794291: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/debug/tracing
1698046515.079798800: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/fuse/connections
1698046515.079804821: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev
1698046515.079809119: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /dev/shm
1698046515.079813908: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev/pts
1698046515.079817986: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev/mqueue
1698046515.079821893: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev/hugepages
1698046515.079826151: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run
1698046515.079830639: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run/user/0
1698046515.079835689: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /proc
1698046515.079851308: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /proc/sys/fs/binfmt_misc
1698046515.079858652: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /proc/sys/fs/binfmt_misc
1698046515.079863140: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /var/lib/nfs/rpc_pipefs
1698046515.079868811: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /root/.cache/bazel/_bazel_root/de3aeab5343b6e0969660d47054e8920/sandbox/linux-sandbox/28/execroot/trpc_cpp
1698046515.079873911: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /root/.cache/bazel/_bazel_root/de3aeab5343b6e0969660d47054e8920/sandbox/linux-sandbox/28/execroot/trpc_cpp
1698046515.079884400: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /tmp
1698046515.079888718: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /dev/shm
1698046515.079906321: src/main/tools/linux-sandbox-pid1.cc:376: calling fork...
1698046515.079998315: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1698046515.080028491: src/main/tools/linux-sandbox-pid1.cc:406: child started with PID 2
gcc: error: trpc/tracing/tracing_factory.cc: Permission denied
gcc: fatal error: no input files

**Comment by zanlichard** [comment]
从/home/lichard/trpc-cpp换到了/root/trpc-cpp 构建过程可以走下去

**Comment by helloopenworld** [comment]
在/root/trpc-cpp目录可以编译通过？在/home/lichard/trpc-cpp目录不行？

**Comment by helloopenworld** [comment]
另外可以看看磁盘空间够不够
