### ISSUE TITLE
请问，这个项目和你们的tars项目有何不同？

### ISSUE THREAD

**Issue by mxmkeep** [trpc-group/trpc-cpp#70]
请问，这个项目和你们的tars项目有何不同？刚开始用tars搭rpc服务，看到刚开源了trpc这项目，有新的东西？更好些？

**Comment by trpc-admin** [comment]
tars除了rpc能力，还带自身体系的服务治理相关能力，trpc主要聚焦rpc框架本身，微服务相关的能力通过插件化对接，开放性更好，现在内部业务主要用trpc了
