### ISSUE TITLE
部署规范是怎么样的?

### ISSUE THREAD

**Issue by zanlichard** [trpc-group/trpc-cpp#72]
部署的目录结构和用途

**Comment by trpc-admin** [comment]
部署规范具体是指哪块？框架的编译安装？

**Comment by zanlichard** [comment]
主要是部署的目录结构如:/usr/local/trpc/bin,conf,data

**Comment by trpc-admin** [comment]
这块是涉及业务程序的运营维护时（比如有专门的服务部署发布平台时），推荐的目录结构，一般不需要关注
