### ISSUE TITLE
如何根据proto文件来生成其他cpp代码

### ISSUE THREAD

**Issue by zanlichard** [trpc-group/trpc-cpp#76]
是使用trpc专有工具来生成,还是使用原始的protoc来生成?

**Comment by weimch** [comment]
使用专有工具生成 [trpc-cmdline](https://github.com/trpc-group/trpc-cmdline#install-trpc-cmdline) 

有多个proto文件并且它们存在相互引用关系，可以参考[基础教程](https://github.com/trpc-group/trpc-cpp/blob/main/docs/zh/basic_tutorial.md) 来组织

简单的调用命令为
```bash
trpc create -l cpp --protofile=forward.proto
```
