### ISSUE TITLE
Fiber能否支持阻塞调用

### ISSUE THREAD

**Issue by shiyiyuedeyu** [trpc-group/trpc-cpp#79]
例如go语言中协程是支持同步的系统调用阻塞当前协程的，Fiber后续是否会支持类似的特性。

**Comment by helloopenworld** [comment]
如果系统调用本身api是同步堵塞的，就会堵塞当前线程，fiber后续暂时不会对同步堵塞线程的api进行hook，让它不堵塞线程

**Comment by shiyiyuedeyu** [comment]
嗯，那在使用的时候，需要和文档里一样外挂一个线程池的方式使用。不过外挂的线程池不受fiber相关控制就是了。
