### ISSUE TITLE
日志打印是否能支持链路追踪

### ISSUE THREAD

**Issue by city-invoker** [trpc-group/trpc-cpp#80]
后台部署有多个server,当一个请求链路存在server1->server2->server3时
此时在三个server上的日志，是否能支持有类似msg_id的标志，可以更加方便地追踪到请求的处理链路
就是框架在请求里自动添加msg_id,logger打印日志时直接根据日志 format配置在每行日志添加msg_id打印

**Comment by bochencwx** [comment]
每条调用链路有一个唯一id，并且该id可以打印到日志中进行区分。这个对应的是可观测领域的链路追踪+日志采集功能。

框架提供的[Telemetry类型插件](https://github.com/trpc-group/trpc-cpp/blob/main/docs/zh/custom_telemetry.md)可以达到这样的目的。可以考虑使用[OpenTelemetry插件](https://github.com/trpc-ecosystem/cpp-telemetry-opentelemetry/tree/main)，或者自行定义一个Telemetry插件。
