### ISSUE TITLE
使用vscode调试如何配置gflags参数?

### ISSUE THREAD

**Issue by cgeffect** [trpc-group/trpc-cpp#86]
使用命令行启动程序, 通过gflags指定参数正常 ./helloworld_svr --config=../conf/trpc_cpp_fiber.yaml
但是如果使用vscode进程调试

示例中HelloWorldServer是继承自TrpcApp, gflags参数
```
DEFINE_string(config, "trpc_cpp_default.yaml", "trpc cpp framework config file");
```
默认值是trpc_cpp_default.yaml, 我在程序的运行目录放置一个trpc_cpp_default.yaml文件,运行报错 
start server with config, for example: /xxx/build/helloworld_svr --config=default.yaml, 看了代码逻辑
```
  if (google::GetCommandLineFlagInfo("config", &info) && info.is_default) {
    std::cerr << "start server with config, for example: " << argv[0] << " --config=default.yaml" << std::endl;
    exit(-1);
  }
```
这里好像又不让使用默认值?

**Comment by cgeffect** [comment]
把这行代码注释掉
![image](https://github.com/trpc-group/trpc-cpp/assets/15692322/2044d566-ab6b-4f7d-bf67-af6c9e04ce32)
重新编译, 在helloworld_svr同级目录放置一个trpc_cpp_default.yaml文件, 执行./helloworld_svr是可以启动成功的

**Comment by weimch** [comment]
需要配置下vscode启动debug时，传入程序的命令行参数

参见：https://code.visualstudio.com/docs/editor/debugging
